### ISSUE TITLE
Bug & Suggestions - Recording Overwrite

### ISSUE THREAD

**Issue by DaveH1234** [TimIsOverpowered/twitch-recorder-go#2]
First off thanks for this Go app, seems to be running nicely from the get go. Couple of things:

1. Can you add a unique identifier or timestamp to the recording mp4 file, if a streamer does 2 streams in one day the first one get's deleted due to the filename being just the date.
2. It'd be nice to be able to specify the format in mp4 or ts for the video.
3. The same above could apply for the date format of the vod, potentially creating our own unique name via the config?
3.  Not a bug but I've been unable to get the chat log integration working, is there anything specific I am missing here other than -chat? Do I need to install ZStandard or similar.

Thanks in advanced, great work.

**Comment by TimIsOverpowered** [comment]
1) After the streamer finishes streaming, [it automatically changes the date to the stream id identifier from twitch.](https://github.com/TimIsOverpowered/twitch-recorder-go/blob/main/main.go#L900) So it should work for multiple streams per day.

2) I can work in that in the future. mp4 was chosen because it is a requirement to upload to youtube.

3) I don't believe this is needed because the stream id identifier is enough.

4) You do need to install ZStandard on the computer you are running it from.

**Comment by evan-sm** [comment]
btw, youtube is fine uploading .ts files.

**Comment by TimIsOverpowered** [comment]
Unless I am missing something in this [article](https://support.google.com/youtube/troubleshooter/2888402). YT doesn't allow m3u8 and ts files. 

Also It doesn't really make sense to upload these kind of containers to YT because they are more suited for HTTP video streaming.
